apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec: # Spec for Deployment
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server-pod
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: laithharb/server:v1

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001



#apiVersion: v1
#kind: Pod
#metadata:
#  name: server-pod
#  labels:
#    app: server
#spec:
#  containers:
#    - name: server
#      image: laithharb/server:v1
#
#
